name: root
channels:
  - conda-forge
dependencies:
  - aubio  # in conda-forge channel (optionnal)
  - h5py
  - ipython
  - jupyter
  - matplotlib
  - networkx
  - numpy
  - pillow
  - python=2.7
  - pyyaml
  - redis
  - scipy
  - simplejson
  - pandas
  - pytables  # named tables in Pypi ...
  - scikit-learn
  - traits
  - Werkzeug
  - yaafe
  - pip:
      - celery<4.0
      - django-angular
      - django-bootstrap-pagination
      - django-bootstrap3
      - django-bower
      - django-celery
      - django-environ
      - django-extensions
      - django==1.6.*
      - djangorestframework==2.*
      - mutagen
      - pympi-ling
      - south
      - uwsgi
      - watchdog
